# Generated by Django 3.2.16 on 2023-02-06 20:07

from django.db import migrations

TAGS = (
    ('Завтрак', ('#FFCF48', 'breakfast')),
    ('Обед', ('#00693E', 'lunch')),
    ('Ужин', ('#ED760E', 'dinner'))
)


def load_tags_data(apps, schema_editor):
    tags = []
    Tag = apps.get_model('recipes', 'Tag')
    for val in TAGS:
        tag = Tag(name=val[0], color=val[1][0], slug=val[1][1])
        tags.append(tag)
    Tag.objects.bulk_create(tags)


def reverse_tags_data(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_tags_data, reverse_tags_data),
    ]
