# Generated by Django 3.2.16 on 2023-01-23 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20221221_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingCart',
            new_name='ShoppingCart',
        ),
    ]
