# Generated by Django 3.2.16 on 2023-02-06 21:24

import csv

from django.db import migrations


def load_ingredients_data(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')

    with open('../../data/ingredients.csv', 'r', encoding='utf-8') as csv_file:
        reader = csv.reader(csv_file)
        ingredients = []

        for row in reader:
            name = row[0]
            ingredient = next((b for b in ingredients if b.name == name), None)
            if not ingredient:
                ingredient = Ingredient(name=row[0], measurement_unit=row[1])
                ingredients.append(ingredient)

        Ingredient.objects.bulk_create(ingredients)


def reverse_ingredients_data(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')

    Ingredient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230206_2307'),
    ]

    operations = [
        migrations.RunPython(load_ingredients_data, reverse_ingredients_data)
    ]
